Repository edgargavioli/projetoIntegrador4, pull requests merged in 2024-11, with the labels that each got.

#95 fix: Corrige os problemas de formatação da acentuação
  controledeestoque/src/main/resources/static/inventario.js
  controledeestoque/src/main/resources/templates/Emprestimo.html
  controledeestoque/src/main/resources/templates/NovoCadastro.html
Labels: bug, frontend

#96 Fix/error floatingbtn
  projeto_integrador/lib/pages/emprestimo_page.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/services/emprestimo_service.dart
Labels: bug, backend, frontend

#97 remove edit button for isSelecting and make tapping the emprestante o…
  controledeestoque/Dockerfile
  controledeestoque/src/main/resources/application.properties
  projeto_integrador/lib/pages/emprestantes_page.dart
Labels: hotfix

#98 fix: emprestantes page e status devolução
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/HtmlController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  controledeestoque/src/main/resources/templates/infoEspecifica.html
  projeto_integrador/lib/pages/emprestantes_page.dart
  projeto_integrador/lib/pages/inventario_page.dart
Labels: hotfix, frontend

#99 Fix/pesquisa e status emprestante
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/EmprestanteController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/Emprestante.java
  projeto_integrador/lib/models/emprestante.dart
  projeto_integrador/lib/pages/emprestante_edit_page.dart
  projeto_integrador/lib/pages/emprestante_registration_page.dart
  projeto_integrador/lib/pages/emprestantes_page.dart
  projeto_integrador/lib/pages/emprestimo_page.dart
  projeto_integrador/lib/pages/inventario_page.dart
Labels: hotfix, frontend
