Repository edgargavioli/projetoIntegrador4, pull requests merged in 2024-10, with the labels that each got.

#72 feat: Adiciona a nova tabela ao banco (emprestante) e adiciona seus c…
  controledeestoque/src/main/java/com/inventario/imobilizado/config/WebConfig.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ActionController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/EmprestanteController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/HtmlController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/LoginController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/Action.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/ActionRequest.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/Emprestante.java
  controledeestoque/src/main/java/com/inventario/imobilizado/repository/EmprestanteInterface.java
  controledeestoque/src/main/resources/application.properties
  controledeestoque/src/main/resources/templates/Avisos.html
  controledeestoque/src/main/resources/templates/Emprestantes.html
  controledeestoque/src/main/resources/templates/Emprestimo.html
  controledeestoque/src/main/resources/templates/NovoCadastro.html
  controledeestoque/src/main/resources/templates/NovoEmprestante.html
  controledeestoque/src/main/resources/templates/Usuarios.html
  controledeestoque/src/main/resources/templates/activeFieldRegistration.html
  controledeestoque/src/main/resources/templates/infoEspecifica.html
  controledeestoque/src/main/resources/templates/infoGeral.html
  controledeestoque/src/main/resources/templates/location.html
  projeto_integrador/macos/Flutter/GeneratedPluginRegistrant.swift
  projeto_integrador/pubspec.lock
Labels: feature, backend

#66 feat: notificações dinâmicas
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  projeto_integrador/android/app/src/main/AndroidManifest.xml
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/models/item_notification.dart
  projeto_integrador/lib/pages/item_registration_page.dart
  projeto_integrador/lib/pages/notifications_page.dart
  projeto_integrador/lib/services/item_service.dart
  projeto_integrador/pubspec.yaml
Labels: feature, frontend

#74 Realização da funcionalidade de busca e filtro nas tela de usuários e…
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/users_page.dart
Labels: feature, frontend

#79 Feat/emprestante
  controledeestoque/src/main/java/com/inventario/imobilizado/config/WebConfig.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/EmprestanteController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/HtmlController.java
  controledeestoque/src/main/resources/templates/Emprestimo.html
Labels: feature, backend

#84 feat: adiciona a funcionalidade na api de emprestar vários itens de u…
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ActionController.java
Labels: feature, backend

#77 Difinindo obrigatoriedade do preenchimento de campos cadastro de itens
  projeto_integrador/lib/models/item.dart
  projeto_integrador/lib/pages/item_registration_page.dart
  projeto_integrador/lib/pages/users_page.dart
Labels: feature, frontend

#85 feat: empréstimo de vários itens
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ActionController.java
  projeto_integrador/lib/models/user.dart
  projeto_integrador/lib/pages/emprestimo_page.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/user_registration_page.dart
  projeto_integrador/lib/services/emprestimo_service.dart
Labels: feature, frontend

#86 fix rota /item/ retornando 500 no emulador
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  controledeestoque/src/main/resources/application.properties
Labels: bug, hotfix

#87 feat: login mantido entre sessões e botão de logout
  projeto_integrador/lib/components/auth_guard.dart
  projeto_integrador/lib/components/custom_app_bar.dart
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/services/auth_service.dart
  projeto_integrador/macos/Flutter/GeneratedPluginRegistrant.swift
  projeto_integrador/pubspec.lock
  projeto_integrador/pubspec.yaml
Labels: feature, frontend

#75 feat: página de emprestantes
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/EmprestanteController.java
  projeto_integrador/lib/components/custom_menu_bar.dart
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/models/emprestante.dart
  projeto_integrador/lib/pages/emprestante_edit_page.dart
  projeto_integrador/lib/pages/emprestante_registration_page.dart
  projeto_integrador/lib/pages/emprestantes_page.dart
  projeto_integrador/lib/pages/home_page.dart
  projeto_integrador/lib/pages/users_page.dart
  projeto_integrador/lib/services/emprestante_service.dart
Labels: feature, frontend

#90 fix: correção formulário
  projeto_integrador/lib/pages/emprestimo_page.dart
Labels: hotfix, frontend

#92 Devolução:
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/services/item_service.dart
Labels: feature, frontend
