Repository edgargavioli/projetoIntegrador4, pull requests merged in 2024-09, with the labels that each got.

#14 doc: Adiciona o link para o figma do projeto
  documentacao/figma.md
Labels: documentação

#13 doc: Adiciona o link do 3W2H para o gerenciamento do projeto
  documentacao/3w2h.md
Labels: documentação

#12 doc: Adiciona o documento Planejamento a documentação
  documentacao/Planejamento .pdf
Labels: documentação

#11 doc: Adicona docuemnto entrevista_cliente a documentação
  documentacao/entrevista_cliente.pdf
Labels: documentação

#28 Feat/blank pages
  projeto_integrador/lib/components/custom_menu_bar.dart
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/pages/home_page.dart
  projeto_integrador/lib/pages/notifications_page.dart
  projeto_integrador/lib/pages/users_page.dart
  projeto_integrador/lib/themes/light_mode.dart
Labels: frontend

#27 fix: Atualização campos obrigatórios
  controledeestoque/.gitignore
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ActionController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/HtmlController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/Action.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/ActionRequest.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/Item.java
  controledeestoque/src/main/java/com/inventario/imobilizado/model/RequestItem.java
  controledeestoque/src/main/resources/application.properties
  controledeestoque/src/main/resources/static/stylesheets/style.css
  controledeestoque/src/main/resources/templates/Emprestimo.html
  controledeestoque/src/main/resources/templates/NovoCadastro.html
  controledeestoque/src/main/resources/templates/infoEspecifica.html
Labels: feature, backend, frontend

#32 feat: navegação agora funcionando
  projeto_integrador/lib/components/custom_menu_bar.dart
  projeto_integrador/lib/pages/home_page.dart
  projeto_integrador/lib/pages/inventario_page.dart
Labels: hotfix

#42 feat: Criação do layout de notificações
  projeto_integrador/lib/components/custom_notification.dart
  projeto_integrador/lib/pages/notifications_page.dart
Labels: frontend

#43 fix: página de usuários não funcionando na navegação
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/pages/users_page.dart
  projeto_integrador/pubspec.lock
Labels: hotfix, frontend

#44 feat: criação tela cadastro de itens
  projeto_integrador/lib/components/custom_select_field.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/item_registration_page.dart
Labels: feature, frontend

#45 feat: ações lista inventário
  projeto_integrador/lib/pages/inventario_page.dart
Labels: feature, frontend

#46 hotfix: navegação para tela de criação de item
  projeto_integrador/lib/main.dart
  projeto_integrador/lib/pages/inventario_page.dart
Labels: hotfix, frontend

#47 Feat/disponibilidade-item-listagem
  projeto_integrador/lib/models/estado.dart
  projeto_integrador/lib/models/item.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/notifications_page.dart
  projeto_integrador/lib/themes/light_mode.dart
  projeto_integrador/pubspec.lock
Labels: feature, frontend

#49 feat: Criação funcionalidade cadastro de itens
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/BrandController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/CategoryController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/LocationController.java
  controledeestoque/src/main/resources/templates/NovoCadastro.html
  projeto_integrador/lib/components/custom_date_field.dart
  projeto_integrador/lib/models/estado.dart
  projeto_integrador/lib/models/item.dart
  projeto_integrador/lib/models/item_list.dart
  projeto_integrador/lib/models/marca.dart
  projeto_integrador/lib/models/modelo.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/item_registration_page.dart
  projeto_integrador/pubspec.yaml
Labels: bug, feature, frontend

#53 Feat/logo loading screen
  projeto_integrador/android/app/src/main/AndroidManifest.xml
  projeto_integrador/android/app/src/main/res/drawable/launch_background.xml
  projeto_integrador/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  projeto_integrador/android/app/src/main/res/mipmap-hdpi/logo.png
  projeto_integrador/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  projeto_integrador/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  projeto_integrador/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  projeto_integrador/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/100.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/102.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/1024.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/114.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/120.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/128.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/144.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/152.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/16.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/167.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/172.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/180.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/196.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/20.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/216.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/256.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/29.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/32.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/40.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/48.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/50.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/512.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/55.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/57.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/58.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/60.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/64.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/66.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/72.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/76.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/80.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/87.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/88.png
  projeto_integrador/ios/Runner/Assets.xcassets/AppIcon.appiconset/_/92.png
  projeto_integrador/pubspec.lock
Labels: feature, frontend

#50 Funcionalidade da tela de notificações
  controledeestoque/src/main/java/com/inventario/imobilizado/controller/ItemController.java
  projeto_integrador/lib/pages/notifications_page.dart
Labels: feature, frontend

#54 refactor: criação services de requisições
  projeto_integrador/lib/models/item_list.dart
  projeto_integrador/lib/models/item_notification.dart
  projeto_integrador/lib/pages/inventario_page.dart
  projeto_integrador/lib/pages/item_registration_page.dart
  projeto_integrador/lib/pages/notifications_page.dart
  projeto_integrador/lib/services/brand_service.dart
  projeto_integrador/lib/services/category_service.dart
  projeto_integrador/lib/services/item_service.dart
  projeto_integrador/lib/services/location_service.dart
  projeto_integrador/lib/services/model_service.dart
Labels: spike, frontend
